# Generated by Django 6.0 on 2026-05-03 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from urllib.parse import quote_plus


def build_avatar_url(name):
    safe_name = quote_plus(name or 'Teryaq User')
    return (
        'https://ui-avatars.com/api/'
        f'?name={safe_name}&background=E2E8F0&color=475569&size=256&rounded=true&bold=true'
    )


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Profile = apps.get_model('store', 'Profile')

    for user in User.objects.all():
        display_name = f'{user.first_name} {user.last_name}'.strip() or user.username
        Profile.objects.get_or_create(
            user=user,
            defaults={
                'role': 'admin' if (user.is_staff or user.is_superuser) else 'user',
                'profile_picture': build_avatar_url(display_name),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_order_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('profile_picture', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
